adminmanage/urls.py
from django.conf.urls import url

from .views import AdminDashboard, AdminAddClass

urlpatterns = [
    url(r'^addclass/$', AdminAddClass.as_view(), name="admin-addclass"),
    url(r'^$', AdminDashboard.as_view(), name="admin-dashboard"),
]

mainapp/urls.py
from django.conf.urls import url

from .views import  Dashboard

urlpatterns = [
    url(r'^$', Dashboard.as_view(),name="Dashboard"),
]

nutantech/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib import admin

from mainapp.views import Home,Dashboard,AdminSignUpView

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url('accounts/', include('django.contrib.auth.urls')),
    url('accounts/admin/', AdminSignUpView.as_view(), name='admin_signup'),

    # For Home Page Redirect and mainapp urls
    url(r'^$', Home.as_view(), name="home"),
    url(r'^dashboard/$', Dashboard.as_view(), name="dashboard"),

    url(r'^adminapp/', include('adminmanage.urls', namespace='adminapp')),
    url(r'^mainapp/', include('mainapp.urls', namespace='mainapp')),
    url(r'^student/', include('studentapp.urls', namespace='student')),


]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

studentapp/urls.py
from django.conf.urls import url

from .views import StudentDashboard

urlpatterns = [
    url(r'^', StudentDashboard.as_view(), name="student-dashboard"),
]

#deepak@mobilecoderz.com

adminmanage/models.py
from django.db import models

# Create your models here.

classapp/models.py
from django.db import models

from common.models import BaseAbstract
from mainapp.models import Sessions, User
from teachersapp.models import TeacherProfile

# Create your models here.
class Class(BaseAbstract):
    sessions    = models.ForeignKey(Sessions, related_name="class_year")
    teacher     = models.OneToOneField(TeacherProfile,on_delete=models.CASCADE)
    classname   = models.CharField(max_length=50)
    classcode   = models.CharField(max_length=20)
    created_by  = models.ForeignKey(User, related_name="class_createdby")

    def __str__(self):
        return self.classname

common/models.py
import datetime
from django.db import models

class BaseAbstract(models.Model):
    created_at = models.DateTimeField(auto_now=False, auto_now_add=False, editable=False)
    updated_at = models.DateTimeField(auto_now_add=False, auto_now=True, editable=False)
    published  = models.BooleanField(default=True)

    class Meta:
        abstract =True

mainapp/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models
from common.models import BaseAbstract

# Create your models here.

class User(AbstractUser):
    is_admin    = models.BooleanField(default=False)
    is_student  = models.BooleanField(default=False)
    is_teacher  = models.BooleanField(default=False)

class School(BaseAbstract):
    name        = models.CharField(max_length=255)
    establish   = models.DateField(auto_now=False, auto_now_add=False)
    affliated_by= models.CharField(max_length=120, default=False)
    board_type  = models.CharField(max_length=100, default=False)
    address     = models.CharField(max_length=255)
    city        = models.CharField(max_length=255)
    state       = models.CharField(max_length=255)
    country     = models.CharField(max_length=255)
    zip         = models.CharField(max_length=255)

    def __str__(self):
        return self.name

class Sessions(BaseAbstract):
    schoolid        = models.ForeignKey(School, related_name='school_session')
    session_years   = models.CharField(max_length=50)
    comments        = models.CharField(max_length=250)

    def __str__(self):
        return self.session_years

teachersapp/models.py
from django.db import models
from common.models import BaseAbstract
from mainapp.models import User

def upload_location(instance, filename):
    #filebase, extension = filename.split(".")
    #return "%s/%s.%s" %(instance.id, instance.id, extension)
    #extension = filename.split(".")
    return "%s/%s" % (instance.id, filename)

class TeacherProfile(BaseAbstract):
    GENDER_CHOICES = (
        ('M', 'Male'),
        ('F', 'Female'),
        ('T', 'Transgender')
    )
    user            = models.OneToOneField(User, models.CASCADE, related_name='teacher_userid')
    first_name      = models.CharField(max_length=100,blank=True)
    middle_name     = models.CharField(max_length=100,blank=True)
    last_name       = models.CharField(max_length=100, blank=True)
    gender          = models.CharField(max_length=1, choices=GENDER_CHOICES)
    dateofbirth     = models.DateField(max_length=10, blank=True, auto_now_add=False, auto_now=False)
    phone           = models.CharField(max_length=15, blank=True)
    email           = models.EmailField(max_length=100, blank=True)
    religion        = models.CharField(max_length=20, blank=True)
    image = models.ImageField(upload_to=upload_location,
                              null=True,
                              blank=True,
                              width_field="width_field",
                              height_field="height_field")
    height_field    = models.IntegerField(default=0)
    width_field     = models.IntegerField(default=0)

    def __str__(self):
        return self.first_name

mainapp/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.db import transaction
from django.forms.utils import ValidationError

from .models import User

class AdminSignUpForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = User

    def save(self, commit=True):
        user = super().save(commit=False)
        user.is_admin = True
        if commit:
            user.save()
        return user

adminmanage/views.py
from django.shortcuts import render, redirect

from django.views.generic import TemplateView

# Create your views here.

class AdminDashboard(TemplateView):
    def get(self, request, *args, **kwargs):
        if request.user.is_authenticated() and request.user.is_admin:
            print(request.user)
            return render(request, 'admindashboard.html',{})

        return redirect("/accounts/login")

class AdminAddClass(TemplateView):
    def get(self, request, *args, **kwargs):
        if request.user.is_authenticated() and request.user.is_admin:
            return render(request, 'adminadd_class.html',{})

        return redirect("/accounts/login")

classapp/views.py
from django.shortcuts import render

# Create your views here.

mainapp/views.py
from django.contrib.auth import login
from django.views.generic import TemplateView, CreateView
from django.contrib import messages

from django.shortcuts import redirect,render

from .forms import AdminSignUpForm
from .models import User

# Create your views here.
class Home(TemplateView):
    template_name = 'home.html'

    def get_context_data(self, *args, **kwargs):
        context = super(Home, self).get_context_data(*args, **kwargs)
        return  context

class Dashboard(TemplateView):
    def get(self, request, *args, **kwargs):
        if request.user.is_authenticated():
            print(request)
            if request.user.is_superuser:
                return redirect("student:student-dashboard")
            elif request.user.is_admin:
                return redirect("adminapp:admin-dashboard")
        else:
            return redirect("/accounts/login")

        return render(request, 'home.html', {})

class AdminSignUpView(CreateView):
    model = User
    form_class = AdminSignUpForm
    template_name = 'registration/signup_form.html'

    def get_context_data(self, **kwargs):
        kwargs['user_type'] = 'admin'
        return super().get_context_data(**kwargs)

    def form_valid(self, form):
        user = form.save()
        login(self.request, user)
        messages.success(self.request, 'Admin Created Successfully!')
        return redirect('admin_signup')

studentapp/views.py
from django.shortcuts import render, redirect

from django.views.generic import TemplateView

# Create your views here.

class StudentDashboard(TemplateView):
    def get(self, request, *args, **kwargs):
        if request.user.is_authenticated():
            if request.user.is_superuser:
                return render(request, 'studentdashboard.html',{})

        return redirect("/accounts/login")



# class StudentDashboard(TemplateView):
#     template_name = 'dashboard.html'
#
#     def get_context_data(self, *args, **kwargs):
#         context = super(StudentDashboard, self).get_context_data(*args, **kwargs)
#         return context

teachersapp/views.py
from django.shortcuts import render

# Create your views here.

adminmanage/templates/adminadd_class.html
{% extends 'dashboard_base.html' %}
{% load static %}
{% block content %}
		<div class="row dashboard-top-nav">
			<div class="col-sm-3 logo">
				<h5><i class="fa fa-book"></i>Admin Dashboard</h5>
			</div>
			<div class="col-sm-4 top-search">
				<div class="search">
					<i class="fa fa-search"></i>
					<input type="text" placeholder="Search">
				</div>
			</div>
			<div class="col-sm-5 notification-area">
				<ul class="top-nav-list">
					<li class="notification dropdown">
						<a href="#" class="dropdown-toggle" data-toggle="dropdown">
							<i class="fa fa-bell-o"></i>
							<span class="badge nav-badge">3</span>
						</a>
						<ul class="dropdown-menu notification-list">
							<li>
								<div class="list-msg">
									<div class="col-xs-2 icon clear-padding">
										<i class="fa fa-trophy"></i>
									</div>
									<div class="col-sm-10 desc">
										<h5><a href="#">Upcoming Sports Meet</a></h5>
										<h6><i class="fa fa-clock-o"></i> 10 min ago</h6>
									</div>
									<div class="clearfix"></div>
								</div>
							</li>
							<li>
								<div class="list-msg">
									<div class="col-xs-2 icon clear-padding">
										<i class="fa fa-paint-brush"></i>
									</div>
									<div class="col-sm-10 desc">
										<h5><a href="#">Fine art workshop</a></h5>
										<h6><i class="fa fa-clock-o"></i> 1 hour ago</h6>
									</div>
									<div class="clearfix"></div>
								</div>
							</li>
							<li>
								<div class="list-msg">
									<div class="col-xs-2 icon clear-padding">
										<i class="fa fa-birthday-cake"></i>
									</div>
									<div class="col-sm-10 desc">
										<h5><a href="#">Annual fest</a></h5>
										<h6><i class="fa fa-clock-o"></i> 1 day ago</h6>
									</div>
									<div class="clearfix"></div>
								</div>
							</li>
							<li>
								<div class="list-msg">
									<div class="col-xs-2 icon clear-padding">
										<i class="fa fa-trophy"></i>
									</div>
									<div class="col-sm-10 desc">
										<h5><a href="#">Upcoming Sports Meet</a></h5>
										<h6><i class="fa fa-clock-o"></i> 10 min ago</h6>
									</div>
									<div class="clearfix"></div>
								</div>
							</li>
							<li>
								<div class="all-notifications">
									<a href="#">VIEW ALL NOTIFICATIONS</a>
								</div>
							</li>
						</ul>
					</li>
					<li class="message dropdown">
						<a href="#" class="dropdown-toggle" data-toggle="dropdown">
							<i class="fa fa-comment-o"></i>
							<span class="badge nav-badge">5</span>
						</a>
						<ul class="dropdown-menu notification-list">
							<li>
								<div class="list-msg">
									<div class="col-xs-2 image clear-padding">
										<img src="assets/img/parent/parent2.jpg" alt="user" />
									</div>
									<div class="col-sm-10 desc">
										<h5><a href="#">John Doe</a></h5>
										<p>Lorem Ipsum is simply dummy text.</p>
										<h6><i class="fa fa-clock-o"></i> 1 day ago</h6>
									</div>
									<div class="clearfix"></div>
								</div>
							</li>
							<li>
								<div class="list-msg">
									<div class="col-xs-2 image clear-padding">
										<img src="assets/img/parent/parent1.jpg" alt="user" />
									</div>
									<div class="col-sm-10 desc">
										<h5><a href="#">Lenore Doe</a></h5>
										<p>Lorem Ipsum is simply dummy text.</p>
										<h6><i class="fa fa-clock-o"></i> 1 day ago</h6>
									</div>
									<div class="clearfix"></div>
								</div>
							</li>
							<li>
								<div class="all-notifications">
									<a href="#">VIEW ALL MESSAGES</a>
								</div>
							</li>
						</ul>
					</li>
					<li class="user dropdown">
						<a href="#" class="dropdown-toggle" data-toggle="dropdown">
							<span><img src="{% static '/img/parent/parent2.jpg' %}" alt="user">JOHN DOE<span class="caret"></span></span>
						</a>
						<ul class="dropdown-menu notification-list">
							<li>
								<a href="#"><i class="fa fa-cogs"></i> SETTINGS</a>
							</li>
							<li>
								<a href="#"><i class="fa fa-users"></i> USER PROFILE</a>
							</li>
							<li>
								<a href="#"><i class="fa fa-key"></i> CHANGE PASSWORD</a>
							</li>
							<li>
								<a href="#"><i class="fa fa-cogs"></i> SETTINGS</a>
							</li>
							<li>
								<div class="all-notifications">
									<a href="{% url 'logout' %}">LOGOUT</a>
								</div>
							</li>
						</ul>
					</li>
				</ul>
			</div>
		</div>

		<div class="parent-wrapper" id="outer-wrapper">
			<!-- SIDE MENU -->
			{% include 'includes/sidebar.html' %}

			<!-- MAIN CONTENT -->
			<div class="main-content" id="content-wrapper">
				<div class="container-fluid">
					<div class="row">
						<div class="col-lg-12 clear-padding-xs">
							<h5 class="page-title"><i class="fa fa-sliders"></i>ALL CALSSES</h5>
							<div class="section-divider"></div>
						</div>
					</div>
					<div class="row">
						<div class="col-lg-12 clear-padding-xs">
							<div class="col-sm-4">
								<div class="dash-item first-dash-item">
									<h6 class="item-title"><i class="fa fa-plus-circle"></i>ADD CLASS</h6>
									<div class="inner-item">
										<div class="dash-form">
											<label class="clear-top-margin"><i class="fa fa-book"></i>CLASS</label>
											<input type="text" placeholder="5 STD" />
											<label><i class="fa fa-code"></i>CLASS CODE</label>
											<input type="text" placeholder="PTH05" />
											<label><i class="fa fa-user-secret"></i>CLASS TEACHER</label>
											<select>
												<option>-- Select --</option>
												<option>Lennore Doe</option>
												<option>John Doe</option>
											</select>
											<label><i class="fa fa-info-circle"></i>DESCRIPTION</label>
											<textarea placeholder="Enter Description Here"></textarea>
											<div>
												<a href="#"><i class="fa fa-paper-plane"></i> CREATE</a>
											</div>
										</div>
										<div class="clearfix"></div>
									</div>
									<div class="clearfix"></div>
								</div>
							</div>
							<div class="col-sm-8">
								<div class="dash-item first-dash-item">
									<h6 class="item-title"><i class="fa fa-sliders"></i>ALL CLASSES</h6>
									<div class="inner-item">
										<table id="attendenceDetailedTable" class="display responsive nowrap" cellspacing="0" width="100%">
											<thead>
												<tr>
													<th><i class="fa fa-book"></i>CLASS</th>
													<th><i class="fa fa-code"></i>CLASS CODE</th>
													<th><i class="fa fa-user-secret"></i>CLASS TEACHER</th>
													<th><i class="fa fa-info-circle"></i>DESCRIPTION</th>
													<th><i class="fa fa-sliders"></i>ACTION</th>
												</tr>
											</thead>
											<tbody>
												<tr>
													<td>5 STD</td>
													<td>PTH05</td>
													<td>Lennore Doe</td>
													<td>DESCRIPTION</td>
													<td class="action-link">
														<a class="edit" href="#" title="Edit" data-toggle="modal" data-target="#editDetailModal"><i class="fa fa-edit"></i></a>
														<a class="delete" href="#" title="Delete" data-toggle="modal" data-target="#deleteDetailModal"><i class="fa fa-remove"></i></a>
													</td>
												</tr>
												<tr>
													<td>4 STD</td>
													<td>PTH04</td>
													<td>John Doe</td>
													<td>DESCRIPTION</td>
													<td class="action-link">
														<a class="edit" href="#" title="Edit" data-toggle="modal" data-target="#editDetailModal"><i class="fa fa-edit"></i></a>
														<a class="delete" href="#" title="Delete" data-toggle="modal" data-target="#deleteDetailModal"><i class="fa fa-remove"></i></a>
													</td>
												</tr>
												<tr>
													<td>7 STD</td>
													<td>PTH07</td>
													<td>John Doe</td>
													<td>DESCRIPTION</td>
													<td class="action-link">
														<a class="edit" href="#" title="Edit" data-toggle="modal" data-target="#editDetailModal"><i class="fa fa-edit"></i></a>
														<a class="delete" href="#" title="Delete" data-toggle="modal" data-target="#deleteDetailModal"><i class="fa fa-remove"></i></a>
													</td>
												</tr>
											</tbody>
										</table>
									</div>
								</div>
							</div>
						</div>
					</div>
				</div>
				<div class="menu-togggle-btn">
					<a href="#menu-toggle" id="menu-toggle"><i class="fa fa-bars"></i></a>
				</div>
				<div class="dash-footer col-lg-12">
					<p>Copyright High School Karni</p>
				</div>

                <!-- Delete Modal -->
				<div id="deleteDetailModal" class="modal fade" role="dialog">
					<div class="modal-dialog">
						<!-- Modal content-->
						<div class="modal-content">
							<div class="modal-header">
								<button type="button" class="close" data-dismiss="modal">&times;</button>
								<h4 class="modal-title"><i class="fa fa-trash"></i>DELETE CLASS</h4>
							</div>
							<div class="modal-body">
								<div class="table-action-box">
									<a href="#" class="save"><i class="fa fa-check"></i>YES</a>
									<a href="#" class="cancel" data-dismiss="modal"><i class="fa fa-ban"></i>CLOSE</a>
								</div>
								<div class="clearfix"></div>
							</div>
						</div>
					</div>
				</div>

				<!--Edit details modal-->
				<div id="editDetailModal" class="modal fade" role="dialog">
					<div class="modal-dialog">
						<!-- Modal content-->
						<div class="modal-content">
							<div class="modal-header">
								<button type="button" class="close" data-dismiss="modal">&times;</button>
								<h4 class="modal-title"><i class="fa fa-edit"></i>EDIT CLASS DETAILS</h4>
							</div>
							<div class="modal-body dash-form">
								<div class="col-sm-4">
									<label class="clear-top-margin"><i class="fa fa-book"></i>CLASS</label>
									<input type="text" placeholder="CLASS" value="5 STD" />
								</div>
								<div class="col-sm-4">
									<label class="clear-top-margin"><i class="fa fa-code"></i>CLASS CODE</label>
									<input type="text" placeholder="CLASS CODE" value="PTH05" />
								</div>
								<div class="col-sm-4">
									<label class="clear-top-margin"><i class="fa fa-user-secret"></i>CLASS TEACHER</label>
									<select>
										<option>-- Select --</option>
										<option>Lennore Doe</option>
										<option>John Doe</option>
									</select>
								</div>
								<div class="clearfix"></div>
								<div class="col-sm-12">
									<label><i class="fa fa-info-circle"></i>DESCRIPTION</label>
									<textarea placeholder="Enter Description Here"></textarea>
								</div>
								<div class="clearfix"></div>
							</div>
							<div class="modal-footer">
								<div class="table-action-box">
									<a href="#" class="save"><i class="fa fa-check"></i>SAVE</a>
									<a href="#" class="cancel" data-dismiss="modal"><i class="fa fa-ban"></i>CLOSE</a>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>

		{% endblock %}

adminmanage/templates/includes/sidebar.html
            <div class="sidebar-nav-wrapper" id="sidebar-wrapper">
				<ul class="sidebar-nav">
					<li>
						<a href="{% url 'adminapp:admin-dashboard' %}"><i class="fa fa-home menu-icon"></i> HOME</a>
					</li>
					<li class="dropdown">
						<a href="#" class="dropdown-toggle" data-toggle="dropdown">
							<i class="fa fa-users menu-icon"></i> STUDENTS <span class="caret"></span>
						</a>
						<ul class="dropdown-menu">
							<li>
								<a href="admin-add-student.html"><i class="fa fa-caret-right"></i>ADD</a>
							</li>
							<li>
								<a href="admin-student-list.html"><i class="fa fa-caret-right"></i>ALL STUDENT  </a>
							</li>
						</ul>
						<div class="clearfix"></div>
					</li>
					<li class="dropdown">
						<a href="#" class="dropdown-toggle" data-toggle="dropdown">
							<i class="fa fa-user-secret menu-icon"></i> TEACHERS <span class="caret"></span>
						</a>
						<ul class="dropdown-menu">
							<li>
								<a href="admin-add-teacher.html"><i class="fa fa-caret-right"></i>ADD</a>
							</li>
							<li>
								<a href="admin-teacher-list.html"><i class="fa fa-caret-right"></i>ALL TEACHER</a>
							</li>
						</ul>
						<div class="clearfix"></div>
					</li>
					<li>
						<a href="message.html"><i class="fa fa-envelope menu-icon"></i> MY MESSAGES</a>
					</li>
					<li>
						<a href="admin-add-announcement.html"><i class="fa fa-bullhorn menu-icon"></i> ANNOUNCEMENTS</a>
					</li>
					<li class="dropdown">
						<a href="#" class="dropdown-toggle" data-toggle="dropdown">
							<i class="fa fa-file-o menu-icon"></i> CLASSES <span class="caret"></span>
						</a>
						<ul class="dropdown-menu">
							<li>
								<a href="{% url 'adminapp:admin-addclass' %}"><i class="fa fa-caret-right"></i>ADD CLASS</a>
							</li>
							<li>
								<a href="admin-add-section.html"><i class="fa fa-caret-right"></i>ADD SECTION</a>
							</li>
							<li>
								<a href="admin-add-class.html"><i class="fa fa-caret-right"></i>VIEW SECTIONS</a>
							</li>
							<li>
								<a href="admin-add-section.html"><i class="fa fa-caret-right"></i>VIEW CLASSES</a>
							</li>
						</ul>
						<div class="clearfix"></div>
					</li>
					<li class="dropdown">
						<a href="#" class="dropdown-toggle" data-toggle="dropdown">
							<i class="fa fa-book menu-icon"></i> SUBJECTS <span class="caret"></span>
						</a>
						<ul class="dropdown-menu">
							<li>
								<a href="admin-add-subject.html"><i class="fa fa-caret-right"></i>ADD</a>
							</li>
							<li>
								<a href="admin-add-subject.html"><i class="fa fa-caret-right"></i>VIEW SUBJECTS</a>
							</li>
						</ul>
						<div class="clearfix"></div>
					</li>
					<li class="dropdown">
						<a href="#" class="dropdown-toggle" data-toggle="dropdown">
							<i class="fa fa-calendar menu-icon"></i> TIMETABLE <span class="caret"></span>
						</a>
						<ul class="dropdown-menu">
							<li>
								<a href="admin-create-timetable.html"><i class="fa fa-caret-right"></i>CREATE</a>
							</li>
							<li>
								<a href="admin-class-timetable.html"><i class="fa fa-caret-right"></i>VIEW</a>
							</li>
						</ul>
						<div class="clearfix"></div>
					</li>
					<li class="dropdown">
						<a href="#" class="dropdown-toggle" data-toggle="dropdown">
							<i class="fa fa-address-card menu-icon"></i> REPORTS <span class="caret"></span>
						</a>
						<ul class="dropdown-menu">
							<li>
								<a href="teacher-attendence-report.html"><i class="fa fa-caret-right"></i>ATTENDENCE</a>
							</li>
							<li>
								<a href="teacher-marks-report.html"><i class="fa fa-caret-right"></i>MARKS</a>
							</li>
						</ul>
						<div class="clearfix"></div>
					</li>
				</ul>
			</div>

templates/dashboard_base.html
{% load staticfiles %}<!DOCTYPE html>
<html lang="en">
<head>

        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta name="author" content="Nutantech Technologies Private Limited">
        <title>High School Karni</title>

        <!-- Styles -->
        <!-- Styles -->
        <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet" media="screen">
		<link href="{% static 'css/owl.carousel.min.css' %}" rel="stylesheet" media="screen">
        <link href="{% static 'css/chartist.min.css' %}" rel="stylesheet" media="screen">
		<link href="{% static 'css/owl.theme.default.min.css' %}" rel="stylesheet" media="screen">
        <link href="{% static 'css/studentdashboard/style.css' %}" rel="stylesheet" media="screen">
        <link href="{% static 'css/custom_home.css' %}" rel="stylesheet" media="screen">

        <!-- Fonts -->
        <link href='https://fonts.googleapis.com/css?family=Open+Sans:400,600,700,800' rel='stylesheet' type='text/css'>
        <link href="{% static 'fonts/font-awesome/fonts/font-awesome.min.41.delay' %}" rel="stylesheet" media="screen">
</head>
<body>
        {% block content %}
        {% endblock %}


<!-- Scripts -->
        <script src="{% static 'js/jQuery_v3_2_0.min.js' %}"></script>
        <script src="{% static 'js/jquery-ui.min.js' %}"></script>
        <script src="{% static 'js/bootstrap.min.js' %}"></script>
		<script src="{% static 'plugins/owl.carousel.min.js' %}"></script>
        <script src="{% static 'plugins/Chart.min.js' %}"></script>
		<script src="{% static 'plugins/jquery.dataTables.min.js' %}"></script>
		<script src="{% static 'plugins/dataTables.responsive.min.js' %}"></script>
        <script src="{% static 'js/studentdashboard_js.js' %}"></script>
</body>
</html>

templates/includes/main_foot_js.html
{% load staticfiles %}

<!-- Scripts -->
        <script src="{% static 'js/jQuery_v3_2_0.min.js' %}"></script>
        <script src="{% static 'js/bootstrap.min.js' %}"></script>
		<script src="{% static 'plugins/owl.carousel.min.js' %}"></script>
        <script src="{% static 'js/js.js' %}"></script>

templates/includes/main_footer.html
		<div class="row footer-row">
			<div class="container">
				<div class="school-logo">
					<i class="fa fa-graduation-cap"></i>
					<h3>High School Karni</h3>
					<h6>BETTER WAY TO LEARN & GROW</h6>
				</div>
				<div class="col-md-4 col-sm-6 footer-item">
					<h5>CONTACT US</h5>
					<p><i class="fa fa-map-marker"></i>Karni, Itkhori, Chatra</p>
					<p><i class="fa fa-mobile"></i> +91 9939744337</p>
					<p><i class="fa fa-envelope"></i>shailesh@highschoolkarni.com</p>
				</div>
				<div class="col-md-2 col-sm-6 footer-item">
					<h5>QUICK LINKS</h5>
					<div class="quick-link-box">
						<a href="#"><i class="fa fa-graduation-cap"></i>Academics</a>
						<a href="#"><i class="fa fa-users"></i>Admission</a>
						<a href="#"><i class="fa fa-calendar"></i>Events</a>
						<a href="#"><i class="fa fa-thumbs-up"></i>Campus Life</a>
					</div>
				</div>
				<div class="clearfix visible-sm"></div>
				<div class="col-md-3 col-sm-6 footer-item">
					<h5>SCHOOL TIMINGS</h5>
					<p><i class="fa fa-clock-o"></i> MON - FRI 9:00 AM - 3:00 PM</p>
					<p><i class="fa fa-clock-o"></i> SAT 9:00 AM - 1:00 PM</p>
				</div>
				<div class="col-md-3 col-sm-6 footer-item">
					<h5>SUBSCRIBE</h5>
					<div class="footer-subscribe">
						<i class="fa fa-envelope"></i></a><input type="text" placeholder="example@highschoolkarni.com" />
					</div>
					<a href="#" class="subscribe-link"><i class="fa fa-paper-plane"></i>SUBMIT</a>
				</div>
			</div>
			<div class="footer-social-row">
				<a href="#"><i class="fa fa-facebook"></i></a>
				<a href="#"><i class="fa fa-twitter"></i></a>
				<a href="#"><i class="fa fa-google-plus"></i></a>
				<a href="#"><i class="fa fa-linkedin"></i></a>
			</div>
		</div>